#!/bin/bash
# Manual test script for Lab Mode sub-menu functionality
# This script helps verify the menu navigation works correctly

echo "=========================================="
echo "Lab Mode Sub-Menu Manual Test Script"
echo "=========================================="
echo ""
echo "This script will help you manually test the Lab Mode sub-menu."
echo ""
echo "Test Cases to Verify:"
echo "1. Main menu displays 3 options (Terminal, Lab, Backtest)"
echo "2. Selecting Lab Mode (option 2) shows sub-menu"
echo "3. Sub-menu has 3 options: Scheduled Training, Manual Training, Back to Main Menu"
echo "4. Scheduled Training option sets FORCE_LAB_NOW=0"
echo "5. Manual Training option sets FORCE_LAB_NOW=1"
echo "6. Back to Main Menu option returns to main menu"
echo ""
echo "To run the test:"
echo "1. Build the project: dotnet build src/UnifiedOrchestrator/UnifiedOrchestrator.csproj"
echo "2. Run with skip mode prompt: SKIP_MODE_PROMPT=1 dotnet run --project src/UnifiedOrchestrator/UnifiedOrchestrator.csproj"
echo "3. OR run interactively: dotnet run --project src/UnifiedOrchestrator/UnifiedOrchestrator.csproj"
echo ""
echo "Expected Flow:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 1: Main Menu appears with 3 options"
echo "  [1] Terminal Mode"
echo "  [2] Lab Mode"
echo "  [3] Backtest Mode"
echo ""
echo "Step 2: Select option 2 (Lab Mode)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Step 3: Lab Mode sub-menu appears with 3 options"
echo "  [1] Scheduled Training (Sunday Only)"
echo "  [2] Manual Training (Run Now)"
echo "  [3] Back to Main Menu"
echo ""
echo "Step 4a: Select option 1 (Scheduled Training)"
echo "  - Should display: 'Lab scheduler will activate and wait for Sunday training window'"
echo "  - Environment: LAB_MODE=1, FORCE_LAB_NOW=0"
echo ""
echo "Step 4b: OR Select option 2 (Manual Training)"
echo "  - Should display: 'Manual training mode activated - Training will start IMMEDIATELY'"
echo "  - Should display: 'Bypassing Sunday schedule restriction'"
echo "  - Environment: LAB_MODE=1, FORCE_LAB_NOW=1"
echo ""
echo "Step 4c: OR Select option 3 (Back to Main Menu)"
echo "  - Should display: 'Returning to main menu...'"
echo "  - Should return to main menu with 3 options"
echo ""
echo "=========================================="
echo "Building the project..."
echo "=========================================="

cd "$(dirname "$0")"
dotnet build src/UnifiedOrchestrator/UnifiedOrchestrator.csproj --configuration Release

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Build successful!"
    echo ""
    echo "To test interactively, run:"
    echo "  dotnet run --project src/UnifiedOrchestrator/UnifiedOrchestrator.csproj --configuration Release"
    echo ""
    echo "To skip the menu and test environment variable detection:"
    echo "  SKIP_MODE_PROMPT=1 LAB_MODE=1 FORCE_LAB_NOW=1 dotnet run --project src/UnifiedOrchestrator/UnifiedOrchestrator.csproj --configuration Release"
else
    echo ""
    echo "❌ Build failed! Please fix compilation errors before testing."
    exit 1
fi
