#!/usr/bin/env python3
"""Data Collection Script - Auto-generated by Bot Mechanic"""

import yfinance as yf
import pandas as pd
from datetime import datetime
import json

def collect_market_data():
    """Collect market data for key symbols"""
    symbols = ['SPY', 'QQQ', 'ES=F', 'NQ=F', 'VIX']
    data = {}
    
    for symbol in symbols:
        try:
            ticker = yf.Ticker(symbol)
            hist = ticker.history(period="1d", interval="5m")
            data[symbol] = {
                'last_price': float(hist['Close'].iloc[-1]),
                'volume': int(hist['Volume'].iloc[-1]),
                'timestamp': datetime.utcnow().isoformat()
            }
        except Exception as e:
            print(f"Error collecting {symbol}: {e}")
    
    return data

if __name__ == "__main__":
    data = collect_market_data()
    print(json.dumps(data, indent=2))
